server:
  port: 8885
  
spring:
  application:
    name: lccl
  #i18国际化
  messages:
    baseFolder : i18n
  ### DB-PG
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/framework?useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: lysss
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    initialSize: 3
    maxActive: 100
    maxIdle: 10
    minIdle: 5
    maxWait: 60000
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    removeAbandoned: true
    removeAbandonedTimeout: 300
    logAbandoned: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 0
    password: 
    pool:
      maxActive: 8
      maxWait: -1
      maxIdle: 8
      minIdle: 0
      nodes: 127.0.0.1:6379,127.0.0.1:6378,127.0.0.1:6380,127.0.0.1:6370,127.0.0.1:6371,127.0.0.1:6372
      maxAttempts: 5 

logging:
  file: logs/log.log
  level: 
    root: info
mybatis:
  typeAliasesPackage: com.example.demo.core.entity
  mapperLocations: classpath:mapper/*.xml

pagehelper : 
  offsetAsPageNum : true
  rowBoundsWithCount : true
  reasonable : true
  autoRuntimeDialect : true
  

