server:
  port: 8885
spring:
  application:
    name: lccl
  #i18国际化
  messages:
    baseFolder: i18n
  ### DB-PG
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/framework?useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: lysss
    driver-class-name: org.postgresql.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 0
    password:
    cluster:
      nodes: 127.0.0.1:6379,127.0.0.1:6378,127.0.0.1:6380,127.0.0.1:6370,127.0.0.1:6371,127.0.0.1:6372

logging:
  file: logs/log.log
  level:
    root: info
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  type-handlers-package: com.example.demo.core.mybatis.sqlHandler.JsonTypeHandler
  #开启驼峰命名法
  mybatis.configuration.map-underscore-to-camel-case: true
  #打印sql语句日志
  logging.level.com.lxj.cache.mappers=: ebug
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: true
  autoRuntimeDialect: true
  

